---
fixtures:
  repositories:
    auditd: "git://github.com/simp/pupmod-simp-auditd"
    augeasproviders_apache: "git://github.com/simp/augeasproviders_apache"
    augeasproviders_core: "git://github.com/simp/augeasproviders_core"
    augeasproviders_grub: "git://github.com/simp/augeasproviders_grub"
    haveged:
      repo: "git://github.com/simp/puppet-haveged"
      branch: "simp-master"
    simplib: "git://github.com/simp/pupmod-simp-simplib"
    simpcat: "git://github.com/simp/pupmod-simp-concat"
    iptables: "git://github.com/simp/pupmod-simp-iptables"
    logrotate: "git://github.com/simp/pupmod-simp-logrotate"
    pki: "git://github.com/simp/pupmod-simp-pki"
    rsync: "git://github.com/simp/pupmod-simp-rsync"
    rsyslog: "git://github.com/simp/pupmod-simp-rsyslog"
    stdlib: "git://github.com/simp/puppetlabs-stdlib"
    compliance: "https://github.com/trevor-vaughan/pupmod-compliance"
  symlinks:
    apache: "#{source_dir}"
